---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: "12.6.0"

platforms:
  - name: centos-6.7
    driver_config:
      image: centos:6.7
      platform: rhel
  - name: centos-6.8
    driver_config:
      image: centos:6.8
      platform: rhel
  - name: centos-7.2
    driver_config:
      image: centos:7
      platform: rhel
  - name: debian-8.5
    driver_config:
      image: debian:8.5
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04

suites:
  - name: default
    run_list:
      - recipe[node]
    attributes:
  - name: diff-version
    run_list:
      - recipe[node]
    attributes:
      node:
        major_version: '0.10'
        version: '0.10.42-1'
